src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Group__c</fullName>
        <label>Expense Group</label>
        <referenceTo>Expense_Group__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Type</label>
        <referenceTo>Expense_Type__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Total__c</fullName>
        <label>Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tip__c</fullName>
        <label>Tip</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expense_Group__c.object
<CustomObject>
    <fields>
        <fullName>EventId__c</fullName>
        <description>The event that the expense group is attached too</description>
        <label>Event Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense Group</label>
    <nameField>
        <displayFormat>EG-{00000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense_Type__c.object
<CustomObject>
    <label>Expense Type</label>
    <nameField>
        <label>Expense Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/eventViewController.cls
public with sharing class eventViewController{

	private final Event event {get; set;}
	private Expense_Group__c[] expense_groups;
	private Expense_Group__c expense_group; 
	public Expense__c[] expenses {get; set;}

	public eventViewController(ApexPages.StandardController stdController){
		
		this.event = (Event) stdController.getRecord();
		this.expense_groups = [SELECT Id FROM Expense_Group__c WHERE EventId__c =: this.event.Id LIMIT 1];

		//load expenses for display
	
		if(this.expense_groups.size() > 0){
			this.expense_group =  this.expense_groups[0];
			this.expenses = [SELECT Id, Amount__c, Comment__c, Expense_Type__c, Expense_Type__r.Name, Expense_Group__c, Total__c, Subtotal__c, Tax_Total__c, Tip__c FROM Expense__c WHERE Expense_Group__c =: this.expense_group.Id];
		} else {
			this.expenses = new List<Expense__c>(); 
		}
	
	}

	public String getEventGroupId(){
		return 'None';
	}

}