src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Group__c</fullName>
        <label>Expense Group</label>
        <referenceTo>Expense_Group__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Type</label>
        <referenceTo>Expense_Type__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Total__c</fullName>
        <label>Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expense_Config__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense Config</label>
    <nameField>
        <label>Expense Config Attribute</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Config</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense_Group__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventId__c</fullName>
        <description>The event that the expense group is attached too</description>
        <label>Event Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense Group</label>
    <nameField>
        <displayFormat>EG-{00000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Tax_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Tax Type</label>
        <referenceTo>Expense_Tax_Type__c</referenceTo>
        <relationshipLabel>Expense Taxes</relationshipLabel>
        <relationshipName>Expense_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Taxes</relationshipLabel>
        <relationshipName>Expense_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Tax</label>
    <nameField>
        <label>Expense Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Taxes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense_Tax_Type__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense Tax Type</label>
    <nameField>
        <label>Expense Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Tax Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense_Type__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Type__c</fullName>
        <inlineHelpText>Specifies how expenses will be entered into the system. For example Millage is entered as the quantity of Miles travelled - for this type of expense quantity is selected. Meals are entered as a dollar amount - for this type of expense amount is selected.</inlineHelpText>
        <label>Entry Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quantity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like users to be able specify taxes for this expense type</inlineHelpText>
        <label>Has Tax</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you would like the expense to be rendered in log format in the monthly report</inlineHelpText>
        <label>Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <inlineHelpText>This is the rate to refund at. 
In the case of amount expenses the rate is the percentage of the cost that is refunded. 
In the case of quantity expenses the rate is the refund amount per item.</inlineHelpText>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense Type</label>
    <nameField>
        <label>Expense Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DataFixtures.cls
public class DataFixtures {

	public static Expense_Type__c[] expense_types;
	public static Map<String, Expense_Type__c> expense_type_map;
	public static Expense_Tax_Type__c[] tax_types;
	public static Expense_Config__c[] configs; 
	public static Event[] lastMonthEvents;
	public static Event[] thisMonthEvents;
	public static Event[] nextMonthEvents;
	public static Expense__c[] thisMonthExpenses;  

	public static void ClearData() {
		
		Expense__c[] expenses = [SELECT Id FROM Expense__c];
		Expense_Tax__c[] expense_tax = [SELECT Id FROM Expense_Tax__c];
		
		Expense_Type__c[] types = [SELECT Id FROM Expense_Type__c]; 
	    Expense_Tax_Type__c[] taxtypes = [SELECT Id FROM Expense_Tax_Type__c]; 
		Expense_Group__c[] groups = [SELECT Id FROM Expense_Group__c];
		Expense_Config__c[] config = [SELECT Id FROM Expense_Config__c];
		
		delete expenses;
		delete expense_tax;
		delete groups;
		delete taxtypes;
		delete types;
		delete config; 
		 
	}


	public static void LoadConfiguration1() {
		
		Document Logo = new Document(Name = 'Logo', FolderId = UserInfo.getUserId());
		insert Logo; 
		
		//Create configuration 
		Expense_Config__c ec1 = new Expense_Config__c(Name = 'Dark Color', Value__c = '000000');
		Expense_Config__c ec2 = new Expense_Config__c(Name = 'Light Color', Value__c = 'FFFFFF');
		Expense_Config__c ec3 = new Expense_Config__c(Name = 'Currency', Value__c = 'Canadian');
		Expense_Config__c ec4 = new Expense_Config__c(Name = 'Logo', Value__c = Logo.Id);
	
		configs = new List<Expense_Config__c>{ec1, ec2, ec3, ec4}; 
		insert configs;
	
		//Create expense types
		Expense_Type__c et1 = new Expense_Type__c(Name = 'Meals', Entry_Type__c = 'Amount', Rate__c = 1, Has_Tax__c = true);
		Expense_Type__c et2 = new Expense_Type__c(Name = 'Hotels', Entry_Type__c = 'Amount', Rate__c = 1, Has_Tax__c = true);	
		Expense_Type__c et3 = new Expense_Type__c(Name = 'Parking', Entry_Type__c = 'Amount', Rate__c = 1, Has_Tax__c = true);
		Expense_Type__c et4 = new Expense_Type__c(Name = 'Rental Car/Fuel', Entry_Type__c = 'Amount', Rate__c = 1, Has_Tax__c = true);
		Expense_Type__c et5 = new Expense_Type__c(Name = 'Mileage', Entry_Type__c = 'Quantity', Rate__c = 0.5, Log__c = true);
		Expense_Type__c et6 = new Expense_Type__c(Name = 'Log Test', Entry_Type__c = 'Quantity', Rate__c = 0.75, Log__c = true);
	
		expense_types = new List<Expense_Type__c>{et1, et2, et3, et4, et5, et6};
		insert expense_types; 
	
	
		//Create tax types		
		Expense_Tax_Type__c ett1 = new Expense_Tax_Type__c(Name = 'GST', Rate__c = 0.05);
		Expense_Tax_Type__c ett2 = new Expense_Tax_Type__c(Name = 'PST', Rate__c = 0.08); 
	
		tax_types = new list<Expense_Tax_Type__c>{ett1, ett2};
		insert tax_types;
		
		expense_type_map = new Map<String, Expense_Type__c>();
		
		for(Expense_Type__c et: expense_types){
			expense_type_map.put(et.Name, et);
		}
	}


	public static void LoadThisMonthEvents(Integer amount) {
		
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
		User u = [SELECT Id, Name FROM User WHERE ProfileId = :p.Id LIMIT 1];
		Opportunity o = new Opportunity(Name = 'Test Op', CloseDate = System.today().addMonths(3), StageName ='Prospecting');
		insert o; 
				
		thisMonthEvents = new List<Event>(); 
		
		for(Integer i=0; i<amount; ++i) {
			DateTime startTime = DateTime.newInstance(System.now().year(), System.now().month(), Math.mod(i,30));
			Date ad = Date.newInstance(System.now().year(), System.now().month(), Math.mod(i,30));
			
			if(Math.mod(i, 2) == 1) {
				thisMonthEvents.add(new Event(OwnerId = u.Id, Subject = 'Test Event', ActivityDate = ad, StartDateTime = startTime, EndDateTime = startTime.addHours(3)));
			} else {
				thisMonthEvents.add(new Event(OwnerId = u.Id, WhatId = o.Id, Subject = 'Test Event', ActivityDate = ad, StartDateTime = startTime, EndDateTime = startTime.addHours(3)));
			}
		}
	
		insert thisMonthEvents; 
		
		Expense_Group__c[] groups = new List<Expense_Group__c>(); 
		
		for(Event e: thisMonthEvents) {
			groups.add(new Expense_Group__c(EventId__c = e.Id, ActivityDate__c = e.ActivityDate));
		}
		
		insert groups;
		
		thisMonthExpenses = new List<Expense__c>();
		for(Expense_Group__c g: groups) {
			Integer number_expenses = Math.round(Math.random()*expense_types.size()); 
						
			for(Integer i=0; i<number_expenses; ++i) {
				thisMonthExpenses.add(new Expense__c(Expense_Group__c= g.Id, Expense_Type__c = expense_types[i].Id, Amount__c = 200, Subtotal__c = 200, Tax_Total__c = 50, Total__c = 250));
			}
			
		}
	
		insert thisMonthExpenses; 
	
	}


}